---
# handlers file for joe_speedboat.guacamole

- name: restart tomcat
  systemd:
    name: tomcat
    state: restarted
    enabled: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
